title: Unidad Planificación Rural Agropecuaria
description: Reposistorio de grupo Análisis
author: Grupo Análisis UPRA
logo: https://avatars0.githubusercontent.com/u/30355763?s=460&v=4
github: https://github.com/UpraAnalisis
about: Grupo Análisis información

baseurl: "https://upraanalisis.github.io"
url: "https://upraanalisis.github.io"

allowsearch: false

disqus_shortname: gaUPRA
google_analytics: UA-72862926-1

share:
  twitter_username: UPRAColombia
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
